//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kursovaya1._1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cafe
    {
        public int ID_cafe { get; set; }
        public Nullable<int> Number_snactypes { get; set; }
        public Nullable<int> Number_drinkstypes { get; set; }
        public Nullable<int> Number_workers { get; set; }
        public string Work_timecafe { get; set; }
        public int ID_cinema { get; set; }
    
        public virtual Cinema Cinema { get; set; }
    }
}
