//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kursovaya1._1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lounge
    {
        public int Lounge_number { get; set; }
        public int Row { get; set; }
        public int Seat { get; set; }
        public int Price { get; set; }
        public int ID_session { get; set; }
    
        public virtual Session Session { get; set; }
    }
}
