//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kursovaya1._1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class KursovaiaEntities1 : DbContext
    {
        private static KursovaiaEntities1 context;
        public KursovaiaEntities1()
            : base("name=KursovaiaEntities1")
        {
        }

        public static KursovaiaEntities1 GetContext()
        {
            if (context == null)
                context = new KursovaiaEntities1();
            return context;
        }


        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Actor> Actors { get; set; }
        public virtual DbSet<Cafe> Cafes { get; set; }
        public virtual DbSet<Cinema> Cinemas { get; set; }
        public virtual DbSet<Director> Directors { get; set; }
        public virtual DbSet<Film> Films { get; set; }
        public virtual DbSet<Lounge> Lounges { get; set; }
        public virtual DbSet<News> News { get; set; }
        public virtual DbSet<Poster> Posters { get; set; }
        public virtual DbSet<Review> Reviews { get; set; }
        public virtual DbSet<Session> Sessions { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Treiler> Treilers { get; set; }
        public virtual DbSet<Sqq_1> Sqq_1 { get; set; }
        public virtual DbSet<Sqq_2> Sqq_2 { get; set; }
        public virtual DbSet<Sqq_11> Sqq_11 { get; set; }
        public virtual DbSet<View_1> View_1 { get; set; }
        public virtual DbSet<View_2> View_2 { get; set; }
        public virtual DbSet<View_3> View_3 { get; set; }
    }
}
