//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kursovaya1._1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Treiler
    {
        public int ID_treiler { get; set; }
        public int ID_film { get; set; }
        public string Treiler1 { get; set; }
    
        public virtual Film Film { get; set; }
    }
}
