//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kursovaya1._1
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_2
    {
        public string Name_cinema { get; set; }
        public string City { get; set; }
        public string Film_name { get; set; }
        public string Session_time { get; set; }
        public int ID_session { get; set; }
        public string Data_session { get; set; }
    }
}
